//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AnioLectivoCalificacionParticipacionHistorico
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public decimal IdAlumno { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdTematica { get; set; }
        public int IdCampoAccion { get; set; }
        public Nullable<decimal> PromedioFinal { get; set; }
    
        public virtual aca_AnioLectivo_Jornada_Curso aca_AnioLectivo_Jornada_Curso { get; set; }
        public virtual aca_AnioLectivo_Tematica aca_AnioLectivo_Tematica { get; set; }
    }
}
